config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  resources :recipes, only: %i[index show]
end

app/models/recipe.rb
class Recipe
  class << self
    def all
      client.entries(content_type: 'recipe')
    end

    def find(id)
      client.entry(id)
    end

    private

    def client
      @client ||= Contentful::Client.new(
        space: ENV['CONTENTFUL_SPACE_ID'],
        access_token: ENV['CONTENTFUL_ACCESS_TOKEN']
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])

    raise ActionController::RoutingError, 'Not Found' if @recipe.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
  def recipe_tags(recipe)
    return [] unless recipe.fields.include?(:tags)

    recipe.tags.map(&:name)
  end

  def chef_name(recipe)
    return 'Unknown' unless recipe.fields.include?(:chef)

    recipe.chef.name
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_recipe_preview.html.erb
<div class="card">
  <div class="card-image">
    <figure class="image is-4by3">
      <%= image_tag(recipe.photo.url, alt: recipe.title) %>
    </figure>
  </div>

  <div class="card-content has-text-centered">
    <div class="subtitle"><%= recipe.title %></div>
  </div>

  <footer class="card-footer">
    <%= link_to 'View full recipe', recipe_path(recipe.id), class: 'card-footer-item has-text-link' %>
  </footer>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <h1 class="title has-text-centered">Recipes</h1>

  <% @recipes.each_slice(4) do |recipes| %>
    <div class="columns is-fullheight">
      <% recipes.each do |recipe| %>
        <div class="column is-3">
          <%= render('recipe_preview', recipe: recipe) %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <h1 id="recipe-title" class="title has-text-centered"><%= @recipe.title %></h1>

  <figure id="recipe-picture" class="image is-16by9">
    <%= image_tag(@recipe.photo.url, alt: @recipe.title) %>
  </figure>

  <% tags = recipe_tags(@recipe) %>

  <% if tags.any? %>
    <div id="recipe-tags" class="mt-2">
      <% tags.each do |tag_name| %>
        <span class="tag is-info"><%= tag_name %></span>
      <% end %>
    </div>
  <% end %>

  <div id="recipe-description" class="content mt-4">
    <%= @recipe.description %>
  </div>

  <p class="title is-5">Chef</p>
  <p id="recipe-chef" class="subtitle is-6"><%= chef_name(@recipe) %></p>
</div>